### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by hendrykeren** [realgam3/CTFDump#1]
Hello Realgam3.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by realgam3** [comment]
Sure! i will be happy to have a logo on my ReadMe! :)

**Comment by hendrykeren** [comment]
i will make better for your project
I will make some improvements to your app

keep listening to xD
respect from me

**Comment by hendrykeren** [comment]
especially in terms of logos

**Comment by hendrykeren** [comment]
Choose one of the logos below,
if you have an additional of logo, you can tell me.

![allcolor](https://user-images.githubusercontent.com/37643051/40890814-3bacdaa4-67a6-11e8-9ab0-2d9d2a5e504a.png)

**Comment by realgam3** [comment]
They are all nice!!!!
I choose the red one :)
Now I need to create an update to the tool, there are some features I thought about adding but now with the new logo its a must! 

Thank you 👍

**Comment by hendrykeren** [comment]
i will help you to update your redme with new logo.

**Comment by hendrykeren** [comment]
Sir please check [#2](https://github.com/realgam3/CTFDump/pull/2)

**Comment by hendrykeren** [comment]
thanks sir already trust me with the change of logo on your application.

Best regards
_@hendrykeren_
