### ISSUE TITLE
Feature request: Download attachments

### ISSUE THREAD

**Issue by radiantly** [realgam3/CTFDump#3]
Many CTFs have files attached, that are part of the challenge, like the example below.

![rtcp tree chall](https://user-images.githubusercontent.com/44368997/73120214-65443c80-3f91-11ea-854d-b910c306810c.png)

 At the moment, CTFDump simply creates files with the the name of the link.

```bash
radiantly@laptop:~/CTFDump/riceteacatpanda.wtf/General Skills/Treeeeeeee$ ls
ReadMe.md
'treemycatisin.7z?token=longrandomtokenthatlookslikeajwttoken'
```

Maybe an `-a` flag can be added where CTFDump downloads all files?

**Comment by realgam3** [comment]
Can you check if it fixed?

**Comment by radiantly** [comment]
Thank you!

**Comment by realgam3** [comment]
No Problem :)
Tell me If you will have another issue
